language: node_js

node_js:
  - stable
  - '6.9'

services:
  - docker

env:
  global:
    - SPEC_AWS_ACCESS_KEY=AwsAccessKey
    - SPEC_AWS_SECRET_KEY=AwsSecretKey
    - SPEC_S3_REGION=us-east-1
    - SPEC_S3_BUCKET=public
    - SPEC_S3_ENDPOINT=127.0.0.1:9000

before_install:
  - pwd
  - mkdir -p .s3/data/{${SPEC_S3_BUCKET},.minio.sys/buckets/${SPEC_S3_BUCKET}}
  - cp specs/s3/${SPEC_S3_BUCKET}/policy.json .s3/data/.minio.sys/buckets/${SPEC_S3_BUCKET}
  - docker pull minio/minio:RELEASE.2018-03-30T00-38-44Z
  - |
    docker run \
    --name s3 \
    -p ${SPEC_S3_ENDPOINT}:9000 \
    -e "MINIO_ACCESS_KEY=${SPEC_AWS_ACCESS_KEY}" \
    -e "MINIO_SECRET_KEY=${SPEC_AWS_SECRET_KEY}" \
    -e "MINIO_REGION=${SPEC_S3_REGION}" \
    -v "${TRAVIS_BUILD_DIR}/.s3/data:/data:rw" \
    -d minio/minio:RELEASE.2018-03-30T00-38-44Z \
    server /data

install:
  - npm install

script:
  - npm run test:cover
  - |
    npm \
    --aws-access-key="${SPEC_AWS_ACCESS_KEY}" \
    --aws-secret-key="${SPEC_AWS_SECRET_KEY}" \
    --s3-region="${SPEC_S3_REGION}" \
    --s3-bucket="${SPEC_S3_BUCKET}" \
    --s3-endpoint="http://${SPEC_S3_ENDPOINT}" \
    --public-base-url="http://${SPEC_S3_ENDPOINT}/${SPEC_S3_BUCKET}" \
    run spec

after_script:
  - npm run test:cover:publish
  - docker logs s3
